Data jpa
yurec26/pet_shelter_boot pull request #1
Opened 2024-12-16 15:09 UTC by yurec26

2024-12-19 17:18 UTC, pas-zhukov requested changes

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/controller/PetController.java
> +        logger.info("Attempt to create pet with name: %s and user_id : %d"
Лучше писать, что мы получили запрос такой-то. Попытка удаления  происходит не здесь

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/controller/PetController.java
> +        logger.info("Attempt to create pet with name: %s and user_id : %d"
Ну и сделать единообразно во всех контроллерах, естественно

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/handler/ExceptionHandlers.java
> +package com.example.pet_shelter_boot.handler;
я бы назвал пакет exception, и можно будет туда еще кастомные эксепшены складывать + хэндлеры для секьюрити в дальнейшем

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/handler/ExceptionHandlers.java
> +    }
На этапе разработки - да, хорошо. Но на проде 500 ошибка не должна присылать подробностей, т.к. это может раскрыть чувствительные и другие данные, подробности реализации

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/handler/ExceptionHandlers.java
> +    }
Тебе это вообще не нужно, т.к. ты используешь `EntityNotFound` для этой ошибки

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/repository/PetRepository.java
> +    );
`id` ты не будешь обновлять, нет смысла в этом параметре. Для остальных надо предусмотреть, что сущность может быть изменена частично. Например, если имя передается, а userId нет (`null`), тогда имя нужно поменять, а вот `userId` трогать не нужно

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/repository/UserRepository.java
> +    );
То же самое что и в петах, касательно `id` и динамического списка параметров

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/repository/UserRepository.java
> +    List<UserEntity> findAllWithPets();
Зачем `@Query`, если можно сделать просто `findAll` и добавить `@EntityGraph`? Не ошибка, но на вопрос жду ответа)

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/service/UserService.java
> +        userRepository.deleteUserFromPets(id);
Нельзя удалять юзера, у которого есть питомцы, т.к. питомцы не должны оставаться бездомными. Нужно делать проверку и возвращать 400, если у юзера есть петы. Нужно сначала их передать кому нибудь, чтоб юзера удалить было можно)

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/repository/UserRepository.java
> +}
В данном случае можно использовать каскадные операции, тогда необходимости в этом методе не будет в целом.

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/service/PetService.java
> +    }
Зачем тут аннотация `@Transactional`? стандартные методы jpa уже транзакционные сами по себе

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/service/PetService.java
> +        );
Здесь тоже вопрос необходимости `@Transactional`

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/service/UserService.java
> +    }
У тебя тут либо true, либо падает ошибка. Я предлагаю передлать в `void throwOnUserDoesNotExist(Integer id)`

2024-12-19 17:18 UTC, pas-zhukov commented on src/main/java/com/example/pet_shelter_boot/service/UserService.java
> +    @Transactional
Тоже убедиться, что необходима транзакция

2024-12-20 16:45 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/controller/PetController.java
> +        logger.info("Attempt to create pet with name: %s and user_id : %d"
Исправил с логгирования факта на логгирование пришедшего запроса

2024-12-20 16:45 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/handler/ExceptionHandlers.java
> +package com.example.pet_shelter_boot.handler;
Есть

2024-12-20 16:45 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/handler/ExceptionHandlers.java
> +    }
Убрал детальное сообщение на абстрактно стандартное

2024-12-20 16:46 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/handler/ExceptionHandlers.java
> +    }
Испрвил

2024-12-20 16:48 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/repository/PetRepository.java
> +    );
переделал запрос на чистом sql с возможными null параметрами

2024-12-20 16:48 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/repository/UserRepository.java
> +    );
Сделаль

2024-12-20 16:49 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/repository/UserRepository.java
> +    List<UserEntity> findAllWithPets();
можно, на этапе освоения такой нейминг, твоё замечание полностью понимаю и не оспариваю.

2024-12-20 16:51 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/service/UserService.java
> +        userRepository.deleteUserFromPets(id);
Я думал что такая ситуация допустима, но раз так, изменил на невозможность удалить юзера, при принадлежащих ему питомца. Для этого нужно раздать всех питомцец, поменяв у них юзер айди

2024-12-20 16:52 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/repository/UserRepository.java
> +}
Удалил это функциональность ввиду прошлого замечания, нельзя удалять пользователей с питомцами

2024-12-20 16:52 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/service/PetService.java
> +    }
Ок принял

2024-12-20 16:52 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/service/PetService.java
> +        );
Ок принял (2)

2024-12-20 16:53 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/service/UserService.java
> +    @Transactional
Убрал

2024-12-20 16:53 UTC, yurec26 commented on src/main/java/com/example/pet_shelter_boot/service/UserService.java
> +    }
Переделал

2024-12-20 19:32 UTC, pas-zhukov approved these changes

2024-12-20 20:52 UTC, merged